@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1c2VyLWF1dGgtc2VydmljZSIsInN1YiI6IjMwOTIyZmFkLTU2NjUtNGFiYS1hMjMwLTRhMDAwOGUwZjM0NyIsImV4cCI6MTczMTI0NDcwOH0.-18zidZiggYpW0vr1X6q2icAos6njYXv-zA8wSlaKfk

### GET all users
GET http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer {{token}}

### POST new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@example.com",
  "firstName": "User",
  "lastName": "One",
  "password": "password"
}

### GET user by username
GET http://localhost:8080/users/profile/user1
Content-Type: application/json
Authorization: Bearer {{token}}

### POST login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password"
}

### PUT update user
PUT http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "user1@mail.com"
}
